[package]
name = "html_to_json"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.20.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = { version = "1.0.127", features = ["preserve_order", "raw_value"] }
