pub const EXPECTED_SHEET1: [&str; 58] = [
    "Form Date",
    "Application Date",
    "Application Number",
    "Agreement Number",
    "Agency Case Number",
    "Insured Name",
    "Insured Surname",
    "Mailing Address",
    "Mailing Address City",
    "Mailing Address State",
    "Mailing Address Zip code",
    "Current Address Years",
    "Current Address Months",
    "Email Address",
    "Website",
    "Phone Number – Home",
    "Phone Number – Office",
    "Phone Number – Fax",
    "Phone Number – Mobile",
    "Company",
    "Company Producer’s Name",
    "Company Producer’s Surname",
    "Company Street Address",
    "Company City",
    "Company State",
    "Company Zip code",
    "List and describe any business owned, operated, or managed by the insured, including any less or’s risk",
    "Number of years in business",
    "Number of full-time employees",
    "Number of part-time employees",
    "Proposed effective date",
    "Current Carrier Name",
    "Expiring Premiums Policy",
    "Expiration Dates",
    "Is the insured a subsidiary of any other entity or does the insured have any subsidiaries?",
    "If Yes Describe",
    "Any policy or coverage declined, cancelled or non-renewed during the prior three years?",
    "If Yes Describe",
    "Is this account new to the producer?",
    "If No how many years has this account been handled?",
    "Has the insured ever declared bankruptcy?",
    "If Yes Give Details",
    "Location 1 : (Complete Address)",
    "Location 2 : (Complete Address)",
    "Location 3 : (Complete Address)",
    "Location 4 : (Complete Address)",
    "Coverage’s Requested",
    "Activity Mooring, Slip & Doc Rental",
    "Activity Storage",
    "Activity Repair",
    "Activity Fuelling",
    "Activity Hauling/Launching",
    "Activity Rental Boats",
    "Activity Rental (Leased Property)",
    "Activity Boat brokerage/fees & commissions",
    "Activity Other Receipts*",
    "Activity Total Receipts",
    "Activity *Please identify source of other receipts:",
];

pub const EXPECTED_SHEET2: [&str; 59] = [
    "Activity  Boat & Engines",
    "Activity Ships Store",
    "Activity Snack Bar/Restaurant",
    "Activity Liquor",
    "Activity Other Sales*",
    "Activity Total Sales",
    "Activity Amount",
    "Activity *Please identify source of other receipts:",
    "General Information Protection at locations",
    "General Information Alarm with outside gong or siren",
    "General Information Alarm with outside gong or siren",
    "General Information Alarm with outside gong or siren",
    "General Information Completely fenced and floodlighted",
    "General Information Completely fenced and floodlighted",
    "General Information Completely fenced and floodlighted",
    "General Information Automatic/emergency fuel shutoff valve",
    "General Information Automatic/emergency fuel shutoff valve",
    "General Information Automatic/emergency fuel shutoff valve",
    "General Information Watchman service after business hours",
    "General Information Watchman service after business hours",
    "General Information Watchman service after business hours",
    "General Information Describe nature & extent of watchman",
    "General Information Describe nature & extent of watchman",
    "General Information Describe nature & extent of watchman",
    "General Information How is boat dealer inventory protected",
    "General Information How is boat dealer inventory protected",
    "General Information How is boat dealer inventory protected",
    "General Information Fire Protection",
    "General Information Paid or Volunteer",
    "General Information Paid or Volunteer",
    "General Information Paid or Volunteer",
    "General Information Distance from location(s)",
    "General Information Distance from location(s)",
    "General Information Distance from location(s)",
    "General Information Public fire hydrants - # and distance",
    "General Information Public fire hydrants - # and distance",
    "General Information Public fire hydrants - # and distance",
    "General Information Public fire mains – size and pressure",
    "General Information Public fire mains – size and pressure",
    "General Information Public fire mains – size and pressure",
    "General Information Local fireboat available",
    "General Information Local fireboat available",
    "General Information Local fireboat available",
    "General Information Describe any private fire protection",
    "General Information Describe any private fire protection",
    "General Information Describe any private fire protection",
    "Marina Operators Any one vessel $",
    "Marina Operators Any one accident or occurrence $",
    "Marina Operators Deductible requested (Minimum $1,000)",
    "Marina Operators Are yachts stored afloat between 12/1 and 4/1?",
    "Marina Operators Are yachts stored inside a building?",
    "Marina Operators Are they on racks?",
    "Marina Operators Sprinkler system?",
    "Marina Operators Building construction",
    "Marina Operators Are yachts stored outside on racks?",
    "Marina Operators If yes, how many yachts?",
    "Marina Operators How many boats?",
    "Marina Operators Are they required to carry full Hull/P&I insurance?",
    "Marina Operators What liability limits?",
];
pub const EXPECTED_SHEET3: [&str; 55] = [
    "Type of vessels",
    "Repair Operations Highest value of any one yacht repaired last year",
    "Repair Operations Describe any commercial ship repair work you do and provide receipts",
    "Repair Operations Are vessel owners allowed to work on their own vessels?",
    "Repair Operations Any sub-contractors used",
    "Repair Operations Do you obtain Certificate of Insurance from sub-contractor?",
    "Repair Operations Is it equivalent to our MOLL limit",
    "Fueling Any fueling for other than boats?",
    "Fueling Who performs fueling of boats?",
    "Fueling Smoking signs posted and enforced?",
    "Fueling Automatic or shut-off switch?",
    "Fueling Additional interests/certificate recipients?",
    "Fueling Name and Address 1",
    "Fueling Interest 1",
    "Fueling Certificate 1",
    "Fueling Name and Address 2",
    "Fueling Interest 2",
    "Fueling Certificate 2",
    "Fueling Name and Address 3",
    "Fueling Interest 3",
    "Fueling Certificate 3",
    "Inventory Building Date",
    "Inventory Building Date",
    "Inventory Building Inventory",
    "Inventory Open Area Date",
    "Inventory Open Area Date",
    "Inventory Open Area  Inventory",
    "Inventory In Water Date",
    "Inventory In Water date",
    "Inventory In Water Inventory",
    "Inventory Building Inventory",
    "Inventory Open Area  Inventory",
    "Inventory In Water Inventory",
    "Inventory Building Inventory",
    "Inventory Open Area  Inventory",
    "Inventory In Water Inventory",
    "Inventory Building Inventory",
    "Inventory Open Area  Inventory",
    "Inventory In Water Inventory",
    "Inventory Building Inventory",
    "Inventory Open Area  Inventory",
    "Inventory In Water Inventory",
    "Are any boats delivered from mfr. at insured’s risk?",
    "If yes, how are they delivered?",
    "Maximum value any one boat $",
    "Maximum value any one delivery $",
    "Are any boats delivered by water to the insured?",
    "If yes, from where?",
    "Total values of boats delivered by insured during the past year: $",
    "By public carrier",
    "Average distance",
    "Maximum",
    "Number of boats delivered to purchaser by water",
    "Average distance",
    "Average value",
];
pub const EXPECTED_SHEET4 :[&str; 39] = [
    "Number Of Boat Shows Annually",
    "Number of boats each show in water or on land",
    "Maximum dollar limit any one show $",
    "Average distance to show",
    "Maximum distance to show Transported by common carrier or own vehicles?",
    "Number per month",
    "Maximum value any one boat",
    "Maximum mph any one boat",
    "Is boat under command of competent employee?",
    "Are demonstrators equipped with full complement of U.S. Coast Guard required safety equipment?",
    "Where are demonstrations performed?",
    "Miles from shore",
    "Distance from dealership",
    "Marina Operators",
    "Boat Dealers",
    "Work Dealers",
    "How many?",
    "Rental Dealers",
    "How many?",
    "Other owned boats (excl boats for sale)",
    "How many?",
    "Limit requested",
    "Deductible Requested",
    "For owned watercraft, are crew covered?",
    "If yes, number of crew",
    "Experience of employees",
    "Please fully describe work boat/rental boat/other owned boat operation if you are requesting P&I coverage for these vessels.",
    "Full describe any operation for which you are requesting coverage for owned watercraft:",
    "Description/Serial Number*",
    "Value",
    "D/A",
    "Description/Serial Number*",
    "Value",
    "Location",
    "Navigation area of above vessel(s)",
    "Location #",
    "Building #",
    "ACV 80 % or",
    "Replacement Cost 90%",
];
pub const EXPECTED_SHEET5: [&str; 49] = [
    "Building Description",
    "Building Limit",
    "Contents Description",
    "Contents Limit",
    "Other Description",
    "Other Limit",
    "Deductible (minimum $1,000)",
    "How is this building used by the insured?",
    "Construction type",
    "Protection Class",
    "Year Built",
    "Total Area",
    "Number of Stories",
    "Other occupancies",
    "Building Improvements",
    "Burglar alarm:",
    "Sprinkler alarm:",
    "Basement:",
    "Requested Limit $ Coinsurance 80%",
    "Agreement Number",
    "Application Number",
    "Agency Case Number",
    "Mortgage Amount $",
    "Amount in bank S$",
    "Amount any other loan $",
    "Amount in other account total $",
    "Insurance $",
    "Shares/bonds",
    "Net assets $",
    "Total assets",
    "Details of treatment",
    "Income (average monthly)",
    "Type of diseases 9",
    "Base salary Gross (p.a.) Net (p.m.) vp $",
    "Income patient 3 $ Treatment value $",
    "Income Guardian $ $ Amount for treatment/operation $",
    "Other income Total value $",
    "Regular income $ Treatment payment $",
    "Government benefits/pension $ Insurance, maintenance, tax & mis $",
    "Part time/casual employment $ Income $",
    "Dividends/Interest $ Life/income replacement insurance $",
    "Commission $ Child maintenance $",
    "Gross (p.a.) X75% Net Other-please specify $",
    "Rent received (p-a,)",
    "$ Total net monthly expenditure",
    "Other $",
    "Treatment & operation $ Total net monthly income $",
    "Home owner value $ Less total monthly expenditure $",
    "Total net monthly income $ Uncommitted monthly income $",
];
